### PR TITLE
Add range functionality

### PR DESCRIPTION
**Pull request by isigmund**

### CODE REVIEW

**Comment by isigmund** [comment]
@ghys As suggested here is the PR to get the range functionality into your repository. Hope it works this way. I'm still not confident that I do things correctly with git.

**Comment by ghys** [comment]
Great, could you please rebase off the tip of the master branch including my commits?

**Comment by isigmund** [comment]
ok I finally managed to do this rebase. It would be great if you you could bump up the version after you merged this so I can refer to he new version when continuing with integrating the range functionality into the knob widget of habpanel

**Comment by ghys** [comment]
Looks good!
Thanks

**Comment by ghys** [comment]
> It would be great if you you could bump up the version

Done: version 0.1.6

**Pull request merged**
